# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Tue Oct  4 20:52:45 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scene = QtWidgets.QLabel(self.centralwidget)
        self.scene.setEnabled(True)
        self.scene.setGeometry(QtCore.QRect(10, 10, 580, 580))
        self.scene.setAutoFillBackground(True)
        self.scene.setFrameShape(QtWidgets.QFrame.Box)
        self.scene.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scene.setLineWidth(1)
        self.scene.setMidLineWidth(0)
        self.scene.setText("")
        self.scene.setScaledContents(True)
        self.scene.setAlignment(QtCore.Qt.AlignCenter)
        self.scene.setWordWrap(False)
        self.scene.setObjectName("scene")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(500, 520, 81, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 25))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFilters = QtWidgets.QMenu(self.menubar)
        self.menuFilters.setObjectName("menuFilters")
        self.spotFilters = QtWidgets.QMenu(self.menuFilters)
        self.spotFilters.setObjectName("spotFilters")
        self.matixFilters = QtWidgets.QMenu(self.menuFilters)
        self.matixFilters.setObjectName("matixFilters")
        self.morphology = QtWidgets.QMenu(self.menuFilters)
        self.morphology.setObjectName("morphology")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setMenuRole(QtWidgets.QAction.AboutQtRole)
        self.openFile.setObjectName("openFile")
        self.saveFile = QtWidgets.QAction(MainWindow)
        self.saveFile.setObjectName("saveFile")
        self.inversion = QtWidgets.QAction(MainWindow)
        self.inversion.setObjectName("inversion")
        self.blue = QtWidgets.QAction(MainWindow)
        self.blue.setObjectName("blue")
        self.gauss = QtWidgets.QAction(MainWindow)
        self.gauss.setObjectName("gauss")
        self.sepia = QtWidgets.QAction(MainWindow)
        self.sepia.setObjectName("sepia")
        self.gray = QtWidgets.QAction(MainWindow)
        self.gray.setObjectName("gray")
        self.bright = QtWidgets.QAction(MainWindow)
        self.bright.setObjectName("bright")
        self.harsness = QtWidgets.QAction(MainWindow)
        self.harsness.setObjectName("harsness")
        self.sobel = QtWidgets.QAction(MainWindow)
        self.sobel.setObjectName("sobel")
        self.feldman = QtWidgets.QAction(MainWindow)
        self.feldman.setObjectName("feldman")
        self.motionblur = QtWidgets.QAction(MainWindow)
        self.motionblur.setObjectName("motionblur")
        self.embossed = QtWidgets.QAction(MainWindow)
        self.embossed.setObjectName("embossed")
        self.glowingEdges = QtWidgets.QAction(MainWindow)
        self.glowingEdges.setObjectName("glowingEdges")
        self.transfer = QtWidgets.QAction(MainWindow)
        self.transfer.setObjectName("transfer")
        self.glass = QtWidgets.QAction(MainWindow)
        self.glass.setObjectName("glass")
        self.reset = QtWidgets.QAction(MainWindow)
        self.reset.setObjectName("reset")
        self.test = QtWidgets.QAction(MainWindow)
        self.test.setObjectName("test")
        self.diffSF = QtWidgets.QAction(MainWindow)
        self.diffSF.setObjectName("diffSF")
        self.diffFS = QtWidgets.QAction(MainWindow)
        self.diffFS.setObjectName("diffFS")
        self.erosion = QtWidgets.QAction(MainWindow)
        self.erosion.setObjectName("erosion")
        self.dilation = QtWidgets.QAction(MainWindow)
        self.dilation.setObjectName("dilation")
        self.opening = QtWidgets.QAction(MainWindow)
        self.opening.setObjectName("opening")
        self.closing = QtWidgets.QAction(MainWindow)
        self.closing.setObjectName("closing")
        self.bin = QtWidgets.QAction(MainWindow)
        self.bin.setObjectName("bin")
        self.menuFile.addAction(self.openFile)
        self.menuFile.addAction(self.saveFile)
        self.spotFilters.addAction(self.inversion)
        self.spotFilters.addAction(self.sepia)
        self.spotFilters.addAction(self.gray)
        self.spotFilters.addAction(self.bright)
        self.spotFilters.addAction(self.transfer)
        self.spotFilters.addAction(self.glass)
        self.spotFilters.addAction(self.bin)
        self.matixFilters.addAction(self.blue)
        self.matixFilters.addAction(self.gauss)
        self.matixFilters.addAction(self.motionblur)
        self.matixFilters.addAction(self.harsness)
        self.matixFilters.addAction(self.sobel)
        self.matixFilters.addAction(self.feldman)
        self.matixFilters.addAction(self.diffSF)
        self.matixFilters.addAction(self.diffFS)
        self.matixFilters.addSeparator()
        self.morphology.addAction(self.erosion)
        self.morphology.addAction(self.dilation)
        self.morphology.addAction(self.opening)
        self.morphology.addAction(self.closing)
        self.menuFilters.addAction(self.spotFilters.menuAction())
        self.menuFilters.addAction(self.matixFilters.menuAction())
        self.menuFilters.addAction(self.morphology.menuAction())
        self.menuFilters.addSeparator()
        self.menuFilters.addAction(self.reset)
        self.menuFilters.addSeparator()
        self.menuFilters.addAction(self.test)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Фильтры и их друзья"))
        self.label.setText(_translate("MainWindow", "(с) Петров"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuFilters.setTitle(_translate("MainWindow", "Фильтры"))
        self.spotFilters.setTitle(_translate("MainWindow", "Точечные"))
        self.matixFilters.setTitle(_translate("MainWindow", "Матричные"))
        self.morphology.setTitle(_translate("MainWindow", "Борьба с шумом"))
        self.openFile.setText(_translate("MainWindow", "Открыть"))
        self.saveFile.setText(_translate("MainWindow", "Сохранить"))
        self.inversion.setText(_translate("MainWindow", "Инверсия"))
        self.blue.setText(_translate("MainWindow", "Размытие"))
        self.gauss.setText(_translate("MainWindow", "Гаусс"))
        self.sepia.setText(_translate("MainWindow", "Сепия"))
        self.gray.setText(_translate("MainWindow", "Чёрно-белое"))
        self.bright.setText(_translate("MainWindow", "Яркость"))
        self.harsness.setText(_translate("MainWindow", "Точность"))
        self.sobel.setText(_translate("MainWindow", "Собель"))
        self.feldman.setText(_translate("MainWindow", "Щарра"))
        self.motionblur.setText(_translate("MainWindow", "Размытие с сдвигом"))
        self.embossed.setText(_translate("MainWindow", "Тиснение"))
        self.glowingEdges.setText(_translate("MainWindow", "Светящие края"))
        self.transfer.setText(_translate("MainWindow", "Волны"))
        self.glass.setText(_translate("MainWindow", "Эффект \"стекла\""))
        self.reset.setText(_translate("MainWindow", "Сброс"))
        self.test.setText(_translate("MainWindow", "Test"))
        self.diffSF.setText(_translate("MainWindow", "Собель - Щарра"))
        self.diffFS.setText(_translate("MainWindow", "Щарра - Собель"))
        self.erosion.setText(_translate("MainWindow", "Сужение"))
        self.dilation.setText(_translate("MainWindow", "Расширение"))
        self.opening.setText(_translate("MainWindow", "Открытие"))
        self.closing.setText(_translate("MainWindow", "Закрытие"))
        self.bin.setText(_translate("MainWindow", "Бинарное"))

